version: '2.4'

volumes:
  mysql_data: 

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 3x4mPl3P4sSW0rD!
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root

  web:
    image: proyecto_integrador/conexion_tec:development
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    entrypoint: /usr/src/bin/dev-entrypoint.sh
    volumes:
      - .:/usr/src
    command: rails server -p 3000 -b 0.0.0.0
    working_dir: /usr/src
    stdin_open: true
    tty: true
    depends_on:
      - mysql
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: "development"
      RACK_ENV: "development"
      RAILS_LOG_TO_STDOUT: "true"
      DATABASE_URL: mysql2://root:3x4mPl3P4sSW0rD!@mysql:3306/conexion_tec_development
